FROM python:3.8-slim

WORKDIR /app

COPY . /app/

ENV AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME} \
    AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY} \
    AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}

EXPOSE 5000

RUN pip install -r requirements.txt

CMD [ "python", "app.py" ]
